#!/usr/bin/env groovy

pipeline {
    agent any

    environment {
        AWS_DEFAULT_REGION='eu-west-1'
    }

    stages {
      stage('Preparation') {
        steps{
            checkout([$class: 'GitSCM',
            branches: [[name: 'origin/shreya_branch']],
            extensions: [[$class: 'WipeWorkspace']],
            userRemoteConfigs: [[url: 'https://github.com/ericechter/seep.git']]
            ])
        }
    }
        stage('validate') {
            steps{
                dir("config-testing"){
                    createVirtualEnv 'env'
                    sh 'aws ec2 describe-instances > sg.json'
                    sh 'results=$(test_tags.py) && echo $results'
                }
            }

        }

    }
}
